<?php if(isset($user)): ?>
    <option value="<?php echo e($user->country); ?>" selected><?php echo e($user->country?? 'Select Country'); ?></option>
<?php else: ?>
    <option value="" selected><?php echo e('Select Country'); ?></option>
<?php endif; ?>

<option value="Afghanistan"><?php echo e(__('Afghanistan')); ?></option>
<option value="Åland Islands"><?php echo e(__('Åland Islands')); ?></option>
<option value="Albania"><?php echo e(__('Albania')); ?></option>
<option value="Algeria"><?php echo e(__('Algeria')); ?></option>
<option value="American Samoa"><?php echo e(__('American Samoa')); ?></option>
<option value="Andorra"><?php echo e(__('Andorra')); ?></option>
<option value="Angola"><?php echo e(__('Angola')); ?></option>
<option value="Anguilla"><?php echo e(__('Anguilla')); ?></option>
<option value="Antarctica"><?php echo e(__('Antarctica')); ?></option>
<option value="Antigua and Barbuda"><?php echo e(__('Antigua and Barbuda')); ?></option>
<option value="Argentina"><?php echo e(__('Argentina')); ?></option>
<option value="Armenia"><?php echo e(__('Armenia')); ?></option>
<option value="Aruba"><?php echo e(__('Aruba')); ?></option>
<option value="Australia"><?php echo e(__('Australia')); ?></option>
<option value="Austria"><?php echo e(__('Austria')); ?></option>
<option value="Azerbaijan"><?php echo e(__('Azerbaijan')); ?></option>
<option value="Bahamas"><?php echo e(__('Bahamas')); ?></option>
<option value="Bahrain"><?php echo e(__('Bahrain')); ?></option>
<option value="Bangladesh"><?php echo e(__('Bangladesh')); ?></option>
<option value="Barbados"><?php echo e(__('Barbados')); ?></option>
<option value="Belarus"><?php echo e(__('Belarus')); ?></option>
<option value="Belgium"><?php echo e(__('Belgium')); ?></option>
<option value="Belize"><?php echo e(__('Belize')); ?></option>
<option value="Benin"><?php echo e(__('Benin')); ?></option>
<option value="Bermuda"><?php echo e(__('Bermuda')); ?></option>
<option value="Bhutan"><?php echo e(__('Bhutan')); ?></option>
<option value="Bolivia"><?php echo e(__('Bolivia')); ?></option>
<option value="Bosnia and Herzegovina"><?php echo e(__('Bosnia and Herzegovina')); ?></option>
<option value="Botswana"><?php echo e(__('Botswana')); ?></option>
<option value="Bouvet Island"><?php echo e(__('Bouvet Island')); ?></option>
<option value="Brazil"><?php echo e(__('Brazil')); ?></option>
<option value="British Indian Ocean Territory"><?php echo e(__('British Indian Ocean Territory')); ?></option>
<option value="Brunei Darussalam"><?php echo e(__('Brunei Darussalam')); ?></option>
<option value="Bulgaria"><?php echo e(__('Bulgaria')); ?></option>
<option value="Burkina Faso"><?php echo e(__('Burkina Faso')); ?></option>
<option value="Burundi"><?php echo e(__('Burundi')); ?></option>
<option value="Cambodia"><?php echo e(__('Cambodia')); ?></option>
<option value="Cameroon"><?php echo e(__('Cameroon')); ?></option>
<option value="Canada"><?php echo e(__('Canada')); ?></option>
<option value="Cape Verde"><?php echo e(__('Cape Verde')); ?></option>
<option value="Cayman Islands"><?php echo e(__('Cayman Islands')); ?></option>
<option value="Central African Republic"><?php echo e(__('Central African Republic')); ?></option>
<option value="Chad"><?php echo e(__('Chad')); ?></option>
<option value="Chile"><?php echo e(__('Chile')); ?></option>
<option value="China"><?php echo e(__('China')); ?></option>
<option value="Christmas Island"><?php echo e(__('Christmas Island')); ?></option>
<option value="Cocos (Keeling) Islands"><?php echo e(__('Cocos (Keeling) Islands')); ?></option>
<option value="Colombia"><?php echo e(__('Colombia')); ?></option>
<option value="Comoros"><?php echo e(__('Comoros')); ?></option>
<option value="Congo"><?php echo e(__('Congo')); ?></option>
<option value="Congo, The Democratic Republic of The"><?php echo e(__('Congo, The Democratic Republic of The')); ?></option>
<option value="Cook Islands"><?php echo e(__('Cook Islands')); ?></option>
<option value="Costa Rica"><?php echo e(__('Costa Rica')); ?></option>
<option value="Cote D'ivoire"><?php echo e(__('Cote D\'ivoire')); ?></option>
<option value="Croatia"><?php echo e(__('Croatia')); ?></option>
<option value="Cuba"><?php echo e(__('Cuba')); ?></option>
<option value="Cyprus"><?php echo e(__('Cyprus')); ?></option>
<option value="Czech Republic"><?php echo e(__('Czech Republic')); ?></option>
<option value="Denmark"><?php echo e(__('Denmark')); ?></option>
<option value="Djibouti"><?php echo e(__('Djibouti')); ?></option>
<option value="Dominica"><?php echo e(__('Dominica')); ?></option>
<option value="Dominican Republic"><?php echo e(__('Dominican Republic')); ?></option>
<option value="Ecuador"><?php echo e(__('Ecuador')); ?></option>
<option value="Egypt"><?php echo e(__('Egypt')); ?></option>
<option value="El Salvador"><?php echo e(__('El Salvador')); ?></option>
<option value="Equatorial Guinea"><?php echo e(__('Equatorial Guinea')); ?></option>
<option value="Eritrea"><?php echo e(__('Eritrea')); ?></option>
<option value="Estonia"><?php echo e(__('Estonia')); ?></option>
<option value="Ethiopia"><?php echo e(__('Ethiopia')); ?></option>
<option value="Falkland Islands (Malvinas)"><?php echo e(__('Falkland Islands (Malvinas')); ?>)</option>
<option value="Faroe Islands"><?php echo e(__('Faroe Islands')); ?></option>
<option value="Fiji"><?php echo e(__('Fiji')); ?></option>
<option value="Finland"><?php echo e(__('Finland')); ?></option>
<option value="France"><?php echo e(__('France')); ?></option>
<option value="French Guiana"><?php echo e(__('French Guiana')); ?></option>
<option value="French Polynesia"><?php echo e(__('French Polynesia')); ?></option>
<option value="French Southern Territories"><?php echo e(__('French Southern Territories')); ?></option>
<option value="Gabon"><?php echo e(__('Gabon')); ?></option>
<option value="Gambia"><?php echo e(__('Gambia')); ?></option>
<option value="Georgia"><?php echo e(__('Georgia')); ?></option>
<option value="Germany"><?php echo e(__('Germany')); ?></option>
<option value="Ghana"><?php echo e(__('Ghana')); ?></option>
<option value="Gibraltar"><?php echo e(__('Gibraltar')); ?></option>
<option value="Greece"><?php echo e(__('Greece')); ?></option>
<option value="Greenland"><?php echo e(__('Greenland')); ?></option>
<option value="Grenada"><?php echo e(__('Grenada')); ?></option>
<option value="Guadeloupe"><?php echo e(__('Guadeloupe')); ?></option>
<option value="Guam"><?php echo e(__('Guam')); ?></option>
<option value="Guatemala"><?php echo e(__('Guatemala')); ?></option>
<option value="Guernsey"><?php echo e(__('Guernsey')); ?></option>
<option value="Guinea"><?php echo e(__('Guinea')); ?></option>
<option value="Guinea-bissau"><?php echo e(__('Guinea-bissau')); ?></option>
<option value="Guyana"><?php echo e(__('Guyana')); ?></option>
<option value="Haiti"><?php echo e(__('Haiti')); ?></option>
<option value="Heard Island and Mcdonald Islands"><?php echo e(__('Heard Island and Mcdonald Islands')); ?></option>
<option value="Holy See (Vatican City State)"><?php echo e(__('Holy See (Vatican City State')); ?>)</option>
<option value="Honduras"><?php echo e(__('Honduras')); ?></option>
<option value="Hong Kong"><?php echo e(__('Hong Kong')); ?></option>
<option value="Hungary"><?php echo e(__('Hungary')); ?></option>
<option value="Iceland"><?php echo e(__('Iceland')); ?></option>
<option value="India"><?php echo e(__('India')); ?></option>
<option value="Indonesia"><?php echo e(__('Indonesia')); ?></option>
<option value="Iran, Islamic Republic of"><?php echo e(__('Iran, Islamic Republic of')); ?></option>
<option value="Iraq"><?php echo e(__('Iraq')); ?></option>
<option value="Ireland"><?php echo e(__('Ireland')); ?></option>
<option value="Isle of Man"><?php echo e(__('Isle of Man')); ?></option>
<option value="Israel"><?php echo e(__('Israel')); ?></option>
<option value="Italy"><?php echo e(__('Italy')); ?></option>
<option value="Jamaica"><?php echo e(__('Jamaica')); ?></option>
<option value="Japan"><?php echo e(__('Japan')); ?></option>
<option value="Jersey"><?php echo e(__('Jersey')); ?></option>
<option value="Jordan"><?php echo e(__('Jordan')); ?></option>
<option value="Kazakhstan"><?php echo e(__('Kazakhstan')); ?></option>
<option value="Kenya"><?php echo e(__('Kenya')); ?></option>
<option value="Kiribati"><?php echo e(__('Kiribati')); ?></option>
<option value="Korea, Democratic People's Republic of"><?php echo e(__('Korea, Democratic People\'s Republic of')); ?></option>
<option value="Korea, Republic of"><?php echo e(__('Korea, Republic of')); ?></option>
<option value="Kuwait"><?php echo e(__('Kuwait')); ?></option>
<option value="Kyrgyzstan"><?php echo e(__('Kyrgyzstan')); ?></option>
<option value="Lao People's Democratic Republic"><?php echo e(__('Lao People\'s Democratic Republic')); ?></option>
<option value="Latvia"><?php echo e(__('Latvia')); ?></option>
<option value="Lebanon"><?php echo e(__('Lebanon')); ?></option>
<option value="Lesotho"><?php echo e(__('Lesotho')); ?></option>
<option value="Liberia"><?php echo e(__('Liberia')); ?></option>
<option value="Libyan Arab Jamahiriya"><?php echo e(__('Libyan Arab Jamahiriya')); ?></option>
<option value="Liechtenstein"><?php echo e(__('Liechtenstein')); ?></option>
<option value="Lithuania"><?php echo e(__('Lithuania')); ?></option>
<option value="Luxembourg"><?php echo e(__('Luxembourg')); ?></option>
<option value="Macao"><?php echo e(__('Macao')); ?></option>
<option value="Macedonia, The Former Yugoslav Republic of"><?php echo e(__('Macedonia, The Former Yugoslav Republic of')); ?></option>
<option value="Madagascar"><?php echo e(__('Madagascar')); ?></option>
<option value="Malawi"><?php echo e(__('Malawi')); ?></option>
<option value="Malaysia"><?php echo e(__('Malaysia')); ?></option>
<option value="Maldives"><?php echo e(__('Maldives')); ?></option>
<option value="Mali"><?php echo e(__('Mali')); ?></option>
<option value="Malta"><?php echo e(__('Malta')); ?></option>
<option value="Marshall Islands"><?php echo e(__('Marshall Islands')); ?></option>
<option value="Martinique"><?php echo e(__('Martinique')); ?></option>
<option value="Mauritania"><?php echo e(__('Mauritania')); ?></option>
<option value="Mauritius"><?php echo e(__('Mauritius')); ?></option>
<option value="Mayotte"><?php echo e(__('Mayotte')); ?></option>
<option value="Mexico"><?php echo e(__('Mexico')); ?></option>
<option value="Micronesia, Federated States of"><?php echo e(__('Micronesia, Federated States of')); ?></option>
<option value="Moldova, Republic of"><?php echo e(__('Moldova, Republic of')); ?></option>
<option value="Monaco"><?php echo e(__('Monaco')); ?></option>
<option value="Mongolia"><?php echo e(__('Mongolia')); ?></option>
<option value="Montenegro"><?php echo e(__('Montenegro')); ?></option>
<option value="Montserrat"><?php echo e(__('Montserrat')); ?></option>
<option value="Morocco"><?php echo e(__('Morocco')); ?></option>
<option value="Mozambique"><?php echo e(__('Mozambique')); ?></option>
<option value="Myanmar"><?php echo e(__('Myanmar')); ?></option>
<option value="Namibia"><?php echo e(__('Namibia')); ?></option>
<option value="Nauru"><?php echo e(__('Nauru')); ?></option>
<option value="Nepal"><?php echo e(__('Nepal')); ?></option>
<option value="Netherlands"><?php echo e(__('Netherlands')); ?></option>
<option value="Netherlands Antilles"><?php echo e(__('Netherlands Antilles')); ?></option>
<option value="New Caledonia"><?php echo e(__('New Caledonia')); ?></option>
<option value="New Zealand"><?php echo e(__('New Zealand')); ?></option>
<option value="Nicaragua"><?php echo e(__('Nicaragua')); ?></option>
<option value="Niger"><?php echo e(__('Niger')); ?></option>
<option value="Nigeria"><?php echo e(__('Nigeria')); ?></option>
<option value="Niue"><?php echo e(__('Niue')); ?></option>
<option value="Norfolk Island"><?php echo e(__('Norfolk Island')); ?></option>
<option value="Northern Mariana Islands"><?php echo e(__('Northern Mariana Islands')); ?></option>
<option value="Norway"><?php echo e(__('Norway')); ?></option>
<option value="Oman"><?php echo e(__('Oman')); ?></option>
<option value="Pakistan"><?php echo e(__('Pakistan')); ?></option>
<option value="Palau"><?php echo e(__('Palau')); ?></option>
<option value="Palestinian Territory, Occupied"><?php echo e(__('Palestinian Territory, Occupied')); ?></option>
<option value="Panama"><?php echo e(__('Panama')); ?></option>
<option value="Papua New Guinea"><?php echo e(__('Papua New Guinea')); ?></option>
<option value="Paraguay"><?php echo e(__('Paraguay')); ?></option>
<option value="Peru"><?php echo e(__('Peru')); ?></option>
<option value="Philippines"><?php echo e(__('Philippines')); ?></option>
<option value="Pitcairn"><?php echo e(__('Pitcairn')); ?></option>
<option value="Poland"><?php echo e(__('Poland')); ?></option>
<option value="Portugal"><?php echo e(__('Portugal')); ?></option>
<option value="Puerto Rico"><?php echo e(__('Puerto Rico')); ?></option>
<option value="Qatar"><?php echo e(__('Qatar')); ?></option>
<option value="Reunion"><?php echo e(__('Reunion')); ?></option>
<option value="Romania"><?php echo e(__('Romania')); ?></option>
<option value="Russian Federation"><?php echo e(__('Russian Federation')); ?></option>
<option value="Rwanda"><?php echo e(__('Rwanda')); ?></option>
<option value="Saint Helena"><?php echo e(__('Saint Helena')); ?></option>
<option value="Saint Kitts and Nevis"><?php echo e(__('Saint Kitts and Nevis')); ?></option>
<option value="Saint Lucia"><?php echo e(__('Saint Lucia')); ?></option>
<option value="Saint Pierre and Miquelon"><?php echo e(__('Saint Pierre and Miquelon')); ?></option>
<option value="Saint Vincent and The Grenadines"><?php echo e(__('Saint Vincent and The Grenadines')); ?></option>
<option value="Samoa"><?php echo e(__('Samoa')); ?></option>
<option value="San Marino"><?php echo e(__('San Marino')); ?></option>
<option value="Sao Tome and Principe"><?php echo e(__('Sao Tome and Principe')); ?></option>
<option value="Saudi Arabia"><?php echo e(__('Saudi Arabia')); ?></option>
<option value="Senegal"><?php echo e(__('Senegal')); ?></option>
<option value="Serbia"><?php echo e(__('Serbia')); ?></option>
<option value="Seychelles"><?php echo e(__('Seychelles')); ?></option>
<option value="Sierra Leone"><?php echo e(__('Sierra Leone')); ?></option>
<option value="Singapore"><?php echo e(__('Singapore')); ?></option>
<option value="Slovakia"><?php echo e(__('Slovakia')); ?></option>
<option value="Slovenia"><?php echo e(__('Slovenia')); ?></option>
<option value="Solomon Islands"><?php echo e(__('Solomon Islands')); ?></option>
<option value="Somalia"><?php echo e(__('Somalia')); ?></option>
<option value="South Africa"><?php echo e(__('South Africa')); ?></option>
<option value="South Georgia and The South Sandwich Islands"><?php echo e(__('South Georgia and The South Sandwich Islands')); ?></option>
<option value="Spain"><?php echo e(__('Spain')); ?></option>
<option value="Sri Lanka"><?php echo e(__('Sri Lanka')); ?></option>
<option value="Sudan"><?php echo e(__('Sudan')); ?></option>
<option value="Suriname"><?php echo e(__('Suriname')); ?></option>
<option value="Svalbard and Jan Mayen"><?php echo e(__('Svalbard and Jan Mayen')); ?></option>
<option value="Swaziland"><?php echo e(__('Swaziland')); ?></option>
<option value="Sweden"><?php echo e(__('Sweden')); ?></option>
<option value="Switzerland"><?php echo e(__('Switzerland')); ?></option>
<option value="Syrian Arab Republic"><?php echo e(__('Syrian Arab Republic')); ?></option>
<option value="Taiwan"><?php echo e(__('Taiwan')); ?></option>
<option value="Tajikistan"><?php echo e(__('Tajikistan')); ?></option>
<option value="Tanzania, United Republic of"><?php echo e(__('Tanzania, United Republic of')); ?></option>
<option value="Thailand"><?php echo e(__('Thailand')); ?></option>
<option value="Timor-leste"><?php echo e(__('Timor-leste')); ?></option>
<option value="Togo"><?php echo e(__('Togo')); ?></option>
<option value="Tokelau"><?php echo e(__('Tokelau')); ?></option>
<option value="Tonga"><?php echo e(__('Tonga')); ?></option>
<option value="Trinidad and Tobago"><?php echo e(__('Trinidad and Tobago')); ?></option>
<option value="Tunisia"><?php echo e(__('Tunisia')); ?></option>
<option value="Turkey"><?php echo e(__('Turkey')); ?></option>
<option value="Turkmenistan"><?php echo e(__('Turkmenistan')); ?></option>
<option value="Turks and Caicos Islands"><?php echo e(__('Turks and Caicos Islands')); ?></option>
<option value="Tuvalu"><?php echo e(__('Tuvalu')); ?></option>
<option value="Uganda"><?php echo e(__('Uganda')); ?></option>
<option value="Ukraine"><?php echo e(__('Ukraine')); ?></option>
<option value="United Arab Emirates"><?php echo e(__('United Arab Emirates')); ?></option>
<option value="United Kingdom"><?php echo e(__('United Kingdom')); ?></option>
<option value="United States"><?php echo e(__('United States')); ?></option>
<option value="United States Minor Outlying Islands"><?php echo e(__('United States Minor Outlying Islands')); ?></option>
<option value="Uruguay"><?php echo e(__('Uruguay')); ?></option>
<option value="Uzbekistan"><?php echo e(__('Uzbekistan')); ?></option>
<option value="Vanuatu"><?php echo e(__('Vanuatu')); ?></option>
<option value="Venezuela"><?php echo e(__('Venezuela')); ?></option>
<option value="Viet Nam"><?php echo e(__('Viet Nam')); ?></option>
<option value="Virgin Islands, British"><?php echo e(__('Virgin Islands, British')); ?></option>
<option value="Virgin Islands, U.S."><?php echo e(__('Virgin Islands, U.S')); ?>.</option>
<option value="Wallis and Futuna"><?php echo e(__('Wallis and Futuna')); ?></option>
<option value="Western Sahara"><?php echo e(__('Western Sahara')); ?></option>
<option value="Yemen"><?php echo e(__('Yemen')); ?></option>
<option value="Zambia"><?php echo e(__('Zambia')); ?></option>
<option value="Zimbabwe"><?php echo e(__('Zimbabwe')); ?></option>
<?php /**PATH C:\Users\zagzo\Downloads\UniServerZ\www\resources\views/default/panel/admin/users/countries.blade.php ENDPATH**/ ?>